// Export all dashboard components for easy imports
export { default as DashboardLayout } from './DashboardLayout';
export { default as Header } from './Header';
export { default as WelcomeHeader } from './WelcomeHeader';
export { default as InboxCard } from './InboxCard';
export { default as IncomeVariationsChart } from './IncomeVariationsChart';
export { default as NetIncomeChart } from './NetIncomeChart';
export { default as SalesCard } from './SalesCard';
export { default as MonthlySalesCard } from './MonthlySalesCard';
export { default as ProjectsTable } from './ProjectsTable';
export { default as Sidebar } from './Sidebar';
